version: '3.8'
services:
  node:
    container_name: toddlearn_node
    image: node:16 
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports: 
      - 8080:8080
    command: runuser node -c "${NPM_COMMAND:-npm run serve}"

